package com.tinysquare.dao.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Coupon implements Serializable {
	
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_coupon.id
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_coupon.shop_id
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    private Long shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_coupon.name
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_coupon.img
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_coupon.category
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    private Byte category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_coupon.amount
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_coupon.start_time
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_coupon.end_time
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_coupon.status
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_coupon.entrydate
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    private Date entrydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_coupon.id
     *
     * @return the value of tiny_coupon.id
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_coupon.id
     *
     * @param id the value for tiny_coupon.id
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_coupon.shop_id
     *
     * @return the value of tiny_coupon.shop_id
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_coupon.shop_id
     *
     * @param shopId the value for tiny_coupon.shop_id
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_coupon.name
     *
     * @return the value of tiny_coupon.name
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_coupon.name
     *
     * @param name the value for tiny_coupon.name
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_coupon.img
     *
     * @return the value of tiny_coupon.img
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_coupon.img
     *
     * @param img the value for tiny_coupon.img
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_coupon.category
     *
     * @return the value of tiny_coupon.category
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    public Byte getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_coupon.category
     *
     * @param category the value for tiny_coupon.category
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    public void setCategory(Byte category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_coupon.amount
     *
     * @return the value of tiny_coupon.amount
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_coupon.amount
     *
     * @param amount the value for tiny_coupon.amount
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_coupon.start_time
     *
     * @return the value of tiny_coupon.start_time
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_coupon.start_time
     *
     * @param startTime the value for tiny_coupon.start_time
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_coupon.end_time
     *
     * @return the value of tiny_coupon.end_time
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_coupon.end_time
     *
     * @param endTime the value for tiny_coupon.end_time
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_coupon.status
     *
     * @return the value of tiny_coupon.status
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_coupon.status
     *
     * @param status the value for tiny_coupon.status
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_coupon.entrydate
     *
     * @return the value of tiny_coupon.entrydate
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    public Date getEntrydate() {
        return entrydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_coupon.entrydate
     *
     * @param entrydate the value for tiny_coupon.entrydate
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }
}