package com.tinysquare.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class CouponCode implements Serializable {
	
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_coupon_code.id
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_coupon_code.code
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_coupon_code.coupon_id
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    private Long couponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_coupon_code.quantity
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_coupon_code.status
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_coupon_code.redeem_time
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    private Date redeemTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_coupon_code.entrydate
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    private Date entrydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_coupon_code.id
     *
     * @return the value of tiny_coupon_code.id
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_coupon_code.id
     *
     * @param id the value for tiny_coupon_code.id
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_coupon_code.code
     *
     * @return the value of tiny_coupon_code.code
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_coupon_code.code
     *
     * @param code the value for tiny_coupon_code.code
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_coupon_code.coupon_id
     *
     * @return the value of tiny_coupon_code.coupon_id
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    public Long getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_coupon_code.coupon_id
     *
     * @param couponId the value for tiny_coupon_code.coupon_id
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_coupon_code.quantity
     *
     * @return the value of tiny_coupon_code.quantity
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_coupon_code.quantity
     *
     * @param quantity the value for tiny_coupon_code.quantity
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_coupon_code.status
     *
     * @return the value of tiny_coupon_code.status
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_coupon_code.status
     *
     * @param status the value for tiny_coupon_code.status
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_coupon_code.redeem_time
     *
     * @return the value of tiny_coupon_code.redeem_time
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    public Date getRedeemTime() {
        return redeemTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_coupon_code.redeem_time
     *
     * @param redeemTime the value for tiny_coupon_code.redeem_time
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    public void setRedeemTime(Date redeemTime) {
        this.redeemTime = redeemTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_coupon_code.entrydate
     *
     * @return the value of tiny_coupon_code.entrydate
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    public Date getEntrydate() {
        return entrydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_coupon_code.entrydate
     *
     * @param entrydate the value for tiny_coupon_code.entrydate
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }
}