package com.tinysquare.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class Favorite implements Serializable {
  
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_favorite.id
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_favorite.user_id
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_favorite.shop_id
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    private Long shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_favorite.status
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_favorite.entrydate
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    private Date entrydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_favorite.id
     *
     * @return the value of tiny_favorite.id
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_favorite.id
     *
     * @param id the value for tiny_favorite.id
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_favorite.user_id
     *
     * @return the value of tiny_favorite.user_id
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_favorite.user_id
     *
     * @param userId the value for tiny_favorite.user_id
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_favorite.shop_id
     *
     * @return the value of tiny_favorite.shop_id
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_favorite.shop_id
     *
     * @param shopId the value for tiny_favorite.shop_id
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_favorite.status
     *
     * @return the value of tiny_favorite.status
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_favorite.status
     *
     * @param status the value for tiny_favorite.status
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_favorite.entrydate
     *
     * @return the value of tiny_favorite.entrydate
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    public Date getEntrydate() {
        return entrydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_favorite.entrydate
     *
     * @param entrydate the value for tiny_favorite.entrydate
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }
}