package com.tinysquare.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class Message implements Serializable {

	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tiny_message.id
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tiny_message.user_id
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tiny_message.title
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tiny_message.subject
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	private String subject;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tiny_message.author
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	private String author;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tiny_message.content
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tiny_message.is_read
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	private Byte isRead;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tiny_message.status
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tiny_message.entrydate
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	private Date entrydate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tiny_message.id
	 * @return  the value of tiny_message.id
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tiny_message.id
	 * @param id  the value for tiny_message.id
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tiny_message.user_id
	 * @return  the value of tiny_message.user_id
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tiny_message.user_id
	 * @param userId  the value for tiny_message.user_id
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tiny_message.title
	 * @return  the value of tiny_message.title
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tiny_message.title
	 * @param title  the value for tiny_message.title
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tiny_message.subject
	 * @return  the value of tiny_message.subject
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	public String getSubject() {
		return subject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tiny_message.subject
	 * @param subject  the value for tiny_message.subject
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	public void setSubject(String subject) {
		this.subject = subject == null ? null : subject.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tiny_message.author
	 * @return  the value of tiny_message.author
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tiny_message.author
	 * @param author  the value for tiny_message.author
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	public void setAuthor(String author) {
		this.author = author == null ? null : author.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tiny_message.content
	 * @return  the value of tiny_message.content
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tiny_message.content
	 * @param content  the value for tiny_message.content
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tiny_message.is_read
	 * @return  the value of tiny_message.is_read
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	public Byte getIsRead() {
		return isRead;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tiny_message.is_read
	 * @param isRead  the value for tiny_message.is_read
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	public void setIsRead(Byte isRead) {
		this.isRead = isRead;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tiny_message.status
	 * @return  the value of tiny_message.status
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tiny_message.status
	 * @param status  the value for tiny_message.status
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tiny_message.entrydate
	 * @return  the value of tiny_message.entrydate
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	public Date getEntrydate() {
		return entrydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tiny_message.entrydate
	 * @param entrydate  the value for tiny_message.entrydate
	 * @mbggenerated  Thu May 05 19:33:13 CST 2016
	 */
	public void setEntrydate(Date entrydate) {
		this.entrydate = entrydate;
	}
}