package com.tinysquare.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class NewsImg implements Serializable {
 
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_news_imgs.id
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_news_imgs.news_id
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    private Long newsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_news_imgs.status
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_news_imgs.url
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_news_imgs.entrydate
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    private Date entrydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_news_imgs.id
     *
     * @return the value of tiny_news_imgs.id
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_news_imgs.id
     *
     * @param id the value for tiny_news_imgs.id
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_news_imgs.news_id
     *
     * @return the value of tiny_news_imgs.news_id
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    public Long getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_news_imgs.news_id
     *
     * @param newsId the value for tiny_news_imgs.news_id
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    public void setNewsId(Long newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_news_imgs.status
     *
     * @return the value of tiny_news_imgs.status
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_news_imgs.status
     *
     * @param status the value for tiny_news_imgs.status
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_news_imgs.url
     *
     * @return the value of tiny_news_imgs.url
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_news_imgs.url
     *
     * @param url the value for tiny_news_imgs.url
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_news_imgs.entrydate
     *
     * @return the value of tiny_news_imgs.entrydate
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    public Date getEntrydate() {
        return entrydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_news_imgs.entrydate
     *
     * @param entrydate the value for tiny_news_imgs.entrydate
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }
}