package com.tinysquare.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class News implements Serializable {
	
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_news.id
     *
     * @mbggenerated Wed Mar 02 22:47:11 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_news.title
     *
     * @mbggenerated Wed Mar 02 22:47:11 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_news.content
     *
     * @mbggenerated Wed Mar 02 22:47:11 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_news.shop_id
     *
     * @mbggenerated Wed Mar 02 22:47:11 CST 2016
     */
    private Long shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_news.status
     *
     * @mbggenerated Wed Mar 02 22:47:11 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_news.entrydate
     *
     * @mbggenerated Wed Mar 02 22:47:11 CST 2016
     */
    private Date entrydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_news.id
     *
     * @return the value of tiny_news.id
     *
     * @mbggenerated Wed Mar 02 22:47:11 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_news.id
     *
     * @param id the value for tiny_news.id
     *
     * @mbggenerated Wed Mar 02 22:47:11 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_news.title
     *
     * @return the value of tiny_news.title
     *
     * @mbggenerated Wed Mar 02 22:47:11 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_news.title
     *
     * @param title the value for tiny_news.title
     *
     * @mbggenerated Wed Mar 02 22:47:11 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_news.content
     *
     * @return the value of tiny_news.content
     *
     * @mbggenerated Wed Mar 02 22:47:11 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_news.content
     *
     * @param content the value for tiny_news.content
     *
     * @mbggenerated Wed Mar 02 22:47:11 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_news.shop_id
     *
     * @return the value of tiny_news.shop_id
     *
     * @mbggenerated Wed Mar 02 22:47:11 CST 2016
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_news.shop_id
     *
     * @param shopId the value for tiny_news.shop_id
     *
     * @mbggenerated Wed Mar 02 22:47:11 CST 2016
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_news.status
     *
     * @return the value of tiny_news.status
     *
     * @mbggenerated Wed Mar 02 22:47:11 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_news.status
     *
     * @param status the value for tiny_news.status
     *
     * @mbggenerated Wed Mar 02 22:47:11 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_news.entrydate
     *
     * @return the value of tiny_news.entrydate
     *
     * @mbggenerated Wed Mar 02 22:47:11 CST 2016
     */
    public Date getEntrydate() {
        return entrydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_news.entrydate
     *
     * @param entrydate the value for tiny_news.entrydate
     *
     * @mbggenerated Wed Mar 02 22:47:11 CST 2016
     */
    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }
}