package com.tinysquare.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class ShopImg implements Serializable {
 
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_shop_img.id
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_shop_img.shop_id
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    private Long shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_shop_img.url
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_shop_img.status
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_shop_img.entrydate
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    private Date entrydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_shop_img.id
     *
     * @return the value of tiny_shop_img.id
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_shop_img.id
     *
     * @param id the value for tiny_shop_img.id
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_shop_img.shop_id
     *
     * @return the value of tiny_shop_img.shop_id
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_shop_img.shop_id
     *
     * @param shopId the value for tiny_shop_img.shop_id
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_shop_img.url
     *
     * @return the value of tiny_shop_img.url
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_shop_img.url
     *
     * @param url the value for tiny_shop_img.url
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_shop_img.status
     *
     * @return the value of tiny_shop_img.status
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_shop_img.status
     *
     * @param status the value for tiny_shop_img.status
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_shop_img.entrydate
     *
     * @return the value of tiny_shop_img.entrydate
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    public Date getEntrydate() {
        return entrydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_shop_img.entrydate
     *
     * @param entrydate the value for tiny_shop_img.entrydate
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }
}