package com.tinysquare.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class UserCoupon implements Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tiny_user_coupon.id
	 *
	 * @mbggenerated Tue Apr 12 22:03:22 CST 2016
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tiny_user_coupon.user_id
	 *
	 * @mbggenerated Tue Apr 12 22:03:22 CST 2016
	 */
	private Long userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tiny_user_coupon.coupon_id
	 *
	 * @mbggenerated Tue Apr 12 22:03:22 CST 2016
	 */
	private Long couponId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tiny_user_coupon.status
	 *
	 * @mbggenerated Tue Apr 12 22:03:22 CST 2016
	 */
	private Byte status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tiny_user_coupon.entrydate
	 *
	 * @mbggenerated Tue Apr 12 22:03:22 CST 2016
	 */
	private Date entrydate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tiny_user_coupon.id
	 *
	 * @return the value of tiny_user_coupon.id
	 *
	 * @mbggenerated Tue Apr 12 22:03:22 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tiny_user_coupon.id
	 *
	 * @param id
	 *            the value for tiny_user_coupon.id
	 *
	 * @mbggenerated Tue Apr 12 22:03:22 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tiny_user_coupon.user_id
	 *
	 * @return the value of tiny_user_coupon.user_id
	 *
	 * @mbggenerated Tue Apr 12 22:03:22 CST 2016
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tiny_user_coupon.user_id
	 *
	 * @param userId
	 *            the value for tiny_user_coupon.user_id
	 *
	 * @mbggenerated Tue Apr 12 22:03:22 CST 2016
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tiny_user_coupon.coupon_id
	 *
	 * @return the value of tiny_user_coupon.coupon_id
	 *
	 * @mbggenerated Tue Apr 12 22:03:22 CST 2016
	 */
	public Long getCouponId() {
		return couponId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tiny_user_coupon.coupon_id
	 *
	 * @param couponId
	 *            the value for tiny_user_coupon.coupon_id
	 *
	 * @mbggenerated Tue Apr 12 22:03:22 CST 2016
	 */
	public void setCouponId(Long couponId) {
		this.couponId = couponId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tiny_user_coupon.status
	 *
	 * @return the value of tiny_user_coupon.status
	 *
	 * @mbggenerated Tue Apr 12 22:03:22 CST 2016
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tiny_user_coupon.status
	 *
	 * @param status
	 *            the value for tiny_user_coupon.status
	 *
	 * @mbggenerated Tue Apr 12 22:03:22 CST 2016
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tiny_user_coupon.entrydate
	 *
	 * @return the value of tiny_user_coupon.entrydate
	 *
	 * @mbggenerated Tue Apr 12 22:03:22 CST 2016
	 */
	public Date getEntrydate() {
		return entrydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tiny_user_coupon.entrydate
	 *
	 * @param entrydate
	 *            the value for tiny_user_coupon.entrydate
	 *
	 * @mbggenerated Tue Apr 12 22:03:22 CST 2016
	 */
	public void setEntrydate(Date entrydate) {
		this.entrydate = entrydate;
	}
}