package com.tinysquare.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {

	private static final long serialVersionUID = -4441113309788015304L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tiny_users.id
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tiny_users.category
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	private Byte category;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tiny_users.account
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	private String account;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tiny_users.imei
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	private String imei;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tiny_users.tel
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	private String tel;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tiny_users.mobile
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	private String mobile;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tiny_users.email
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	private String email;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tiny_users.avatar
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	private String avatar;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tiny_users.password
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	private String password;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tiny_users.platform
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	private Byte platform;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tiny_users.version
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	private String version;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tiny_users.status
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	private Byte status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tiny_users.entrydate
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	private Date entrydate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tiny_users.id
	 *
	 * @return the value of tiny_users.id
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tiny_users.id
	 *
	 * @param id
	 *            the value for tiny_users.id
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tiny_users.category
	 *
	 * @return the value of tiny_users.category
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public Byte getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tiny_users.category
	 *
	 * @param category
	 *            the value for tiny_users.category
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public void setCategory(Byte category) {
		this.category = category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tiny_users.account
	 *
	 * @return the value of tiny_users.account
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tiny_users.account
	 *
	 * @param account
	 *            the value for tiny_users.account
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public void setAccount(String account) {
		this.account = account == null ? null : account.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tiny_users.imei
	 *
	 * @return the value of tiny_users.imei
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public String getImei() {
		return imei;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tiny_users.imei
	 *
	 * @param imei
	 *            the value for tiny_users.imei
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public void setImei(String imei) {
		this.imei = imei == null ? null : imei.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tiny_users.tel
	 *
	 * @return the value of tiny_users.tel
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tiny_users.tel
	 *
	 * @param tel
	 *            the value for tiny_users.tel
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public void setTel(String tel) {
		this.tel = tel == null ? null : tel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tiny_users.mobile
	 *
	 * @return the value of tiny_users.mobile
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tiny_users.mobile
	 *
	 * @param mobile
	 *            the value for tiny_users.mobile
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tiny_users.email
	 *
	 * @return the value of tiny_users.email
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tiny_users.email
	 *
	 * @param email
	 *            the value for tiny_users.email
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tiny_users.avatar
	 *
	 * @return the value of tiny_users.avatar
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public String getAvatar() {
		return avatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tiny_users.avatar
	 *
	 * @param avatar
	 *            the value for tiny_users.avatar
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public void setAvatar(String avatar) {
		this.avatar = avatar == null ? null : avatar.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tiny_users.password
	 *
	 * @return the value of tiny_users.password
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tiny_users.password
	 *
	 * @param password
	 *            the value for tiny_users.password
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tiny_users.platform
	 *
	 * @return the value of tiny_users.platform
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public Byte getPlatform() {
		return platform;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tiny_users.platform
	 *
	 * @param platform
	 *            the value for tiny_users.platform
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public void setPlatform(Byte platform) {
		this.platform = platform;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tiny_users.version
	 *
	 * @return the value of tiny_users.version
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tiny_users.version
	 *
	 * @param version
	 *            the value for tiny_users.version
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public void setVersion(String version) {
		this.version = version == null ? null : version.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tiny_users.status
	 *
	 * @return the value of tiny_users.status
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tiny_users.status
	 *
	 * @param status
	 *            the value for tiny_users.status
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tiny_users.entrydate
	 *
	 * @return the value of tiny_users.entrydate
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public Date getEntrydate() {
		return entrydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tiny_users.entrydate
	 *
	 * @param entrydate
	 *            the value for tiny_users.entrydate
	 *
	 * @mbggenerated Mon Feb 22 20:47:49 CST 2016
	 */
	public void setEntrydate(Date entrydate) {
		this.entrydate = entrydate;
	}
}