package com.tinysquare.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class VipCard implements Serializable {
	
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_vip_card.id
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_vip_card.user_id
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_vip_card.shop_id
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    private Long shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_vip_card.card_num
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    private String cardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_vip_card.img
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_vip_card.brief
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    private String brief;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_vip_card.points
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    private Long points;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_vip_card.user_times
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    private Integer userTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_vip_card.category
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    private Byte category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_vip_card.is_default
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    private Byte isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_vip_card.status
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiny_vip_card.entrydate
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    private Date entrydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_vip_card.id
     *
     * @return the value of tiny_vip_card.id
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_vip_card.id
     *
     * @param id the value for tiny_vip_card.id
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_vip_card.user_id
     *
     * @return the value of tiny_vip_card.user_id
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_vip_card.user_id
     *
     * @param userId the value for tiny_vip_card.user_id
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_vip_card.shop_id
     *
     * @return the value of tiny_vip_card.shop_id
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_vip_card.shop_id
     *
     * @param shopId the value for tiny_vip_card.shop_id
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_vip_card.card_num
     *
     * @return the value of tiny_vip_card.card_num
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    public String getCardNum() {
        return cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_vip_card.card_num
     *
     * @param cardNum the value for tiny_vip_card.card_num
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    public void setCardNum(String cardNum) {
        this.cardNum = cardNum == null ? null : cardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_vip_card.img
     *
     * @return the value of tiny_vip_card.img
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_vip_card.img
     *
     * @param img the value for tiny_vip_card.img
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_vip_card.brief
     *
     * @return the value of tiny_vip_card.brief
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_vip_card.brief
     *
     * @param brief the value for tiny_vip_card.brief
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    public void setBrief(String brief) {
        this.brief = brief == null ? null : brief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_vip_card.points
     *
     * @return the value of tiny_vip_card.points
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    public Long getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_vip_card.points
     *
     * @param points the value for tiny_vip_card.points
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    public void setPoints(Long points) {
        this.points = points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_vip_card.user_times
     *
     * @return the value of tiny_vip_card.user_times
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    public Integer getUserTimes() {
        return userTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_vip_card.user_times
     *
     * @param userTimes the value for tiny_vip_card.user_times
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    public void setUserTimes(Integer userTimes) {
        this.userTimes = userTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_vip_card.category
     *
     * @return the value of tiny_vip_card.category
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    public Byte getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_vip_card.category
     *
     * @param category the value for tiny_vip_card.category
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    public void setCategory(Byte category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_vip_card.is_default
     *
     * @return the value of tiny_vip_card.is_default
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    public Byte getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_vip_card.is_default
     *
     * @param isDefault the value for tiny_vip_card.is_default
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    public void setIsDefault(Byte isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_vip_card.status
     *
     * @return the value of tiny_vip_card.status
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_vip_card.status
     *
     * @param status the value for tiny_vip_card.status
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiny_vip_card.entrydate
     *
     * @return the value of tiny_vip_card.entrydate
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    public Date getEntrydate() {
        return entrydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiny_vip_card.entrydate
     *
     * @param entrydate the value for tiny_vip_card.entrydate
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }
}