package com.tinysquare.dao.mapper;

import com.tinysquare.dao.entity.Coupon;
import com.tinysquare.dao.entity.CouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_coupon
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    int countByExample(CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_coupon
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    int deleteByExample(CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_coupon
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_coupon
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    int insert(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_coupon
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    int insertSelective(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_coupon
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    List<Coupon> selectByExample(CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_coupon
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    Coupon selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_coupon
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    int updateByExampleSelective(@Param("record") Coupon record, @Param("example") CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_coupon
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    int updateByExample(@Param("record") Coupon record, @Param("example") CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_coupon
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    int updateByPrimaryKeySelective(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_coupon
     *
     * @mbggenerated Wed Apr 13 21:19:35 CST 2016
     */
    int updateByPrimaryKey(Coupon record);
}