package com.tinysquare.dao.mapper;

import com.tinysquare.dao.entity.CouponCode;
import com.tinysquare.dao.entity.CouponCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CouponCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_coupon_code
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    int countByExample(CouponCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_coupon_code
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    int deleteByExample(CouponCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_coupon_code
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_coupon_code
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    int insert(CouponCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_coupon_code
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    int insertSelective(CouponCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_coupon_code
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    List<CouponCode> selectByExample(CouponCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_coupon_code
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    CouponCode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_coupon_code
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") CouponCode record, @Param("example") CouponCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_coupon_code
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    int updateByExample(@Param("record") CouponCode record, @Param("example") CouponCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_coupon_code
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    int updateByPrimaryKeySelective(CouponCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_coupon_code
     *
     * @mbggenerated Fri Apr 15 19:34:25 CST 2016
     */
    int updateByPrimaryKey(CouponCode record);
}