package com.tinysquare.dao.mapper;

import com.tinysquare.dao.entity.Favorite;
import com.tinysquare.dao.entity.FavoriteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FavoriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_favorite
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    int countByExample(FavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_favorite
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    int deleteByExample(FavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_favorite
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_favorite
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    int insert(Favorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_favorite
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    int insertSelective(Favorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_favorite
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    List<Favorite> selectByExample(FavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_favorite
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    Favorite selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_favorite
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") Favorite record, @Param("example") FavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_favorite
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    int updateByExample(@Param("record") Favorite record, @Param("example") FavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_favorite
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    int updateByPrimaryKeySelective(Favorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_favorite
     *
     * @mbggenerated Sun Mar 13 21:40:25 CST 2016
     */
    int updateByPrimaryKey(Favorite record);
}