package com.tinysquare.dao.mapper;

import com.tinysquare.dao.entity.NewsImg;
import com.tinysquare.dao.entity.NewsImgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewsImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_news_imgs
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    int countByExample(NewsImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_news_imgs
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    int deleteByExample(NewsImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_news_imgs
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_news_imgs
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    int insert(NewsImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_news_imgs
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    int insertSelective(NewsImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_news_imgs
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    List<NewsImg> selectByExample(NewsImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_news_imgs
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    NewsImg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_news_imgs
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    int updateByExampleSelective(@Param("record") NewsImg record, @Param("example") NewsImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_news_imgs
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    int updateByExample(@Param("record") NewsImg record, @Param("example") NewsImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_news_imgs
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    int updateByPrimaryKeySelective(NewsImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_news_imgs
     *
     * @mbggenerated Tue Mar 01 21:29:05 CST 2016
     */
    int updateByPrimaryKey(NewsImg record);
}