package com.tinysquare.dao.mapper;

import com.tinysquare.dao.entity.News;
import com.tinysquare.dao.entity.NewsExample;
import com.tinysquare.dao.entityex.NewsItem;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface NewsMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tiny_news
	 *
	 * @mbggenerated Tue Mar 01 21:12:17 CST 2016
	 */
	int countByExample(NewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tiny_news
	 *
	 * @mbggenerated Tue Mar 01 21:12:17 CST 2016
	 */
	int deleteByExample(NewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tiny_news
	 *
	 * @mbggenerated Tue Mar 01 21:12:17 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tiny_news
	 *
	 * @mbggenerated Tue Mar 01 21:12:17 CST 2016
	 */
	int insert(News record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tiny_news
	 *
	 * @mbggenerated Tue Mar 01 21:12:17 CST 2016
	 */
	int insertSelective(News record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tiny_news
	 *
	 * @mbggenerated Tue Mar 01 21:12:17 CST 2016
	 */
	List<News> selectByExample(NewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tiny_news
	 *
	 * @mbggenerated Tue Mar 01 21:12:17 CST 2016
	 */
	News selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tiny_news
	 *
	 * @mbggenerated Tue Mar 01 21:12:17 CST 2016
	 */
	int updateByExampleSelective(@Param("record") News record, @Param("example") NewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tiny_news
	 *
	 * @mbggenerated Tue Mar 01 21:12:17 CST 2016
	 */
	int updateByExample(@Param("record") News record, @Param("example") NewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tiny_news
	 *
	 * @mbggenerated Tue Mar 01 21:12:17 CST 2016
	 */
	int updateByPrimaryKeySelective(News record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tiny_news
	 *
	 * @mbggenerated Tue Mar 01 21:12:17 CST 2016
	 */
	int updateByPrimaryKey(News record);

	/**
	 * 查询用户附近店铺的消息
	 * 
	 * @param params
	 *            #{lng},#{lat},#{pageBegin},#{pageSize}
	 * @return
	 */
	List<NewsItem> selectOrderByDistance(Map<String, Object> params);

	/**
	 * 查询用户附近店铺的消息总条数
	 *            
	 * @return
	 */
	int countOrderByDistance(Map<String, Object> params);

	/**
	 * 查询用户收藏的消息
	 * 
	 * @param params
	 *            #{userId},#{lng},#{lat},#{pageBegin},#{pageSize}
	 * @return
	 */
	List<NewsItem> selectByFavorite(Map<String, Object> params);

	/**
	 * 查询用户收藏的消息总条数
	 * 
	 * @param params
	 *            #{userId}
	 * @return
	 */
	int countByFavorite(Map<String, Object> params);

	/**
	 * 根据店铺id查询店铺的消息
	 * 
	 * @param params
	 *            #{shopId},#{pageBegin},#{pageSize}
	 * @return
	 */
	List<NewsItem> selectByShopId(Map<String, Object> params);

	/**
	 * 根据店铺id查询店铺的消息总条数
	 * 
	 * @param params
	 *            #{shopId}
	 * @return
	 */
	int countByShopId(Map<String, Object> params);
}