package com.tinysquare.dao.mapper;

import com.tinysquare.dao.entity.ShopImg;
import com.tinysquare.dao.entity.ShopImgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_shop_img
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    int countByExample(ShopImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_shop_img
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    int deleteByExample(ShopImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_shop_img
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_shop_img
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    int insert(ShopImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_shop_img
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    int insertSelective(ShopImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_shop_img
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    List<ShopImg> selectByExample(ShopImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_shop_img
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    ShopImg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_shop_img
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    int updateByExampleSelective(@Param("record") ShopImg record, @Param("example") ShopImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_shop_img
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    int updateByExample(@Param("record") ShopImg record, @Param("example") ShopImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_shop_img
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    int updateByPrimaryKeySelective(ShopImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_shop_img
     *
     * @mbggenerated Thu Mar 03 20:17:08 CST 2016
     */
    int updateByPrimaryKey(ShopImg record);
}