package com.tinysquare.dao.mapper;

import com.tinysquare.dao.entity.User;
import com.tinysquare.dao.entity.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_users
     *
     * @mbggenerated Sun Feb 28 16:19:40 CST 2016
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_users
     *
     * @mbggenerated Sun Feb 28 16:19:40 CST 2016
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_users
     *
     * @mbggenerated Sun Feb 28 16:19:40 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_users
     *
     * @mbggenerated Sun Feb 28 16:19:40 CST 2016
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_users
     *
     * @mbggenerated Sun Feb 28 16:19:40 CST 2016
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_users
     *
     * @mbggenerated Sun Feb 28 16:19:40 CST 2016
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_users
     *
     * @mbggenerated Sun Feb 28 16:19:40 CST 2016
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_users
     *
     * @mbggenerated Sun Feb 28 16:19:40 CST 2016
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_users
     *
     * @mbggenerated Sun Feb 28 16:19:40 CST 2016
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_users
     *
     * @mbggenerated Sun Feb 28 16:19:40 CST 2016
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_users
     *
     * @mbggenerated Sun Feb 28 16:19:40 CST 2016
     */
    int updateByPrimaryKey(User record);
}