package com.tinysquare.dao.mapper;

import com.tinysquare.dao.entity.VipCard;
import com.tinysquare.dao.entity.VipCardExample;
import com.tinysquare.dao.entityex.VipCardItem;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface VipCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_vip_card
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    int countByExample(VipCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_vip_card
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    int deleteByExample(VipCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_vip_card
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_vip_card
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    int insert(VipCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_vip_card
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    int insertSelective(VipCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_vip_card
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    List<VipCard> selectByExample(VipCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_vip_card
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    VipCard selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_vip_card
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    int updateByExampleSelective(@Param("record") VipCard record, @Param("example") VipCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_vip_card
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    int updateByExample(@Param("record") VipCard record, @Param("example") VipCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_vip_card
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    int updateByPrimaryKeySelective(VipCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiny_vip_card
     *
     * @mbggenerated Wed Apr 13 20:58:17 CST 2016
     */
    int updateByPrimaryKey(VipCard record);
    
    /**
	 * 根据用户id查询会员卡
	 * 
	 * @param params
	 *            #{userId}
	 * @return
	 */
	List<VipCardItem> selectByUserId(Map<String, Object> params);
}